#!/usr/bin/env node
/**
 * Regenerate CONTRIBUTORS.md and CONTRIBUTORS.ko.md from who has actually
 * landed a change.
 *
 * Hand-maintaining this would work until the first time somebody forgot, and
 * forgetting a contributor is worse than having no list at all. Same shape as
 * `third-party.mjs`: generated, checked in, and CI fails when it is stale.
 *
 * Read from the GitHub API rather than from `git log`, because the log cannot
 * answer the question honestly:
 *
 *   - One person appears as several authors. `Presentj94@gmail.com` and
 *     `presentj94@gmail.com` differ by one capital letter and are one person;
 *     `msnodeve` has also committed as `Groot`, while `Groot(김명석)` is a
 *     different person entirely.
 *   - `Co-authored-by:` trailers are not commit authors. One contributor
 *     reached `main` only that way and a count over the log loses them.
 *   - The log holds email addresses, including work and university ones.
 *     Publishing those because they were convenient is not something this
 *     repository gets to do.
 *
 * The API answers with logins, already merged per person, and no addresses.
 *
 * Owners come from `.github/CODEOWNERS` rather than a list kept here, so the
 * two cannot disagree about who they are.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const REPO = "zero-shelter/zero-shelter";

const owners = ownersFromCodeowners();
const logins = await fetchContributors();

const isOwner = (login) => owners.has(login.toLowerCase());
const byName = (a, b) => a.toLowerCase().localeCompare(b.toLowerCase());

const ownerList = logins.filter(isOwner).sort(byName);
const contributorList = logins.filter((login) => !isOwner(login)).sort(byName);

writeFileSync(join(root, "CONTRIBUTORS.md"), english(), "utf8");
writeFileSync(join(root, "CONTRIBUTORS.ko.md"), korean(), "utf8");

console.log(
  `CONTRIBUTORS.md · CONTRIBUTORS.ko.md: ${ownerList.length} owners, ${contributorList.length} contributors`,
);

/**
 * No counts, deliberately.
 *
 * Ordering people by commits turns a thank-you into a scoreboard, and the
 * person who fixed one line reads it as a measure of how little they did.
 * Alphabetical says the same thing about everyone.
 */
function list(people) {
  return people.map((login) => `- [@${login}](https://github.com/${login})`).join("\n");
}

function english() {
  return `# Contributors

Everyone whose work is in this repository. Generated by \`npm run contributors\`
from the commits that reached \`main\`, so nobody has to remember to add a name.
Alphabetical, without commit counts: one line and one hundred lines are both
work this project did not have to do itself.

Korean: [CONTRIBUTORS.ko.md](./CONTRIBUTORS.ko.md)

## Owners

Named in [\`.github/CODEOWNERS\`](./.github/CODEOWNERS), review every pull
request, and answer for what ships.

${list(ownerList)}

## Contributors

${list(contributorList)}

Bots are left out — a list of people is the point.

Not here and think you should be? Open an issue. The generator reads GitHub's
own record of who has commits on \`main\`, so a change that landed under a
different account is the likeliest reason, and that is worth fixing rather than
working around.
`;
}

function korean() {
  return `# 기여자

이 저장소에 작업이 들어간 모든 사람입니다. \`npm run contributors\`가
\`main\`에 도달한 커밋에서 생성하므로 이름을 손으로 추가할 일이 없습니다.
커밋 수 없이 알파벳순입니다 — 한 줄이든 백 줄이든 이 프로젝트가 스스로
하지 않아도 됐던 일입니다.

영어: [CONTRIBUTORS.md](./CONTRIBUTORS.md)

## Owner

[\`.github/CODEOWNERS\`](./.github/CODEOWNERS)에 적힌 사람들입니다. 모든 풀
리퀘스트를 리뷰하고, 배포된 것에 대해 답합니다.

${list(ownerList)}

## 기여자

${list(contributorList)}

봇은 제외합니다. 사람 목록이라는 것이 요점입니다.

여기 없는데 있어야 한다고 생각되면 이슈를 열어 주세요. 생성기는 \`main\`에
커밋이 있는 사람에 대한 GitHub 자체 기록을 읽으므로, 다른 계정으로 들어간
변경이 가장 흔한 이유입니다. 그건 우회할 것이 아니라 고칠 문제입니다.
`;
}

/** `* @a @b @c` — the same file that decides who is asked to review. */
function ownersFromCodeowners() {
  const raw = readFileSync(join(root, ".github", "CODEOWNERS"), "utf8");
  const found = new Set();

  for (const line of raw.split("\n")) {
    const body = line.split("#")[0];
    for (const [, login] of body.matchAll(/@([A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)/g)) {
      found.add(login.toLowerCase());
    }
  }

  if (found.size === 0) throw new Error(".github/CODEOWNERS names nobody");
  return found;
}

/**
 * Fails loudly rather than writing a shorter list.
 *
 * A network blip that quietly dropped half the names would be committed by
 * whoever ran this next, and the diff — people disappearing — is exactly what
 * nobody wants to discover later.
 */
async function fetchContributors() {
  const token = process.env["GITHUB_TOKEN"] ?? process.env["GH_TOKEN"];
  const people = [];

  for (let page = 1; page <= 10; page += 1) {
    const response = await fetch(
      `https://api.github.com/repos/${REPO}/contributors?per_page=100&page=${page}`,
      {
        headers: {
          accept: "application/vnd.github+json",
          "user-agent": "zero-shelter-contributors",
          ...(token === undefined ? {} : { authorization: `Bearer ${token}` }),
        },
      },
    );

    if (!response.ok) {
      throw new Error(
        `GitHub API answered ${response.status} for ${REPO} contributors. ` +
          "Not writing a partial list — rerun rather than commit a shorter one.",
      );
    }

    const batch = await response.json();
    if (batch.length === 0) break;
    // `type` is "Bot" for dependabot and friends. None are here today, and the
    // day one is, it should not arrive in a file about people.
    people.push(...batch.filter((entry) => entry.type !== "Bot").map((entry) => entry.login));
    if (batch.length < 100) break;
  }

  if (people.length === 0) throw new Error("GitHub returned no contributors, which cannot be right");
  return people;
}
